/** Authored triangle topology follows the silhouette; adjacent regions may share boundary vertices. */
export const PUPPY_FACES = [
  ["head", "eye", "nose", "bridge"], ["head", "eye", "bridge", "brow"],
  ["head", "eye", "brow", "forehead"], ["head", "eye", "forehead", "crown"],
  ["head", "eye", "crown", "cheek"], ["head", "eye", "cheek", "jaw"],
  ["head", "eye", "jaw", "muzzle"], ["head", "eye", "muzzle", "nose"],
  ["ears", "crown", "earRoot", "earFold"], ["ears", "earFold", "earRoot", "earOuter"],
  ["ears", "earFold", "earOuter", "earBend"], ["ears", "earFold", "earBend", "earTip"],
  ["ears", "earFold", "earTip", "earInner"],
  ["frame", "cheek", "chest", "earTip"], ["frame", "earTip", "chest", "neck"],
  ["frame", "earOuter", "neck", "earBend"], ["frame", "earBend", "neck", "earTip"],
  ["frame", "neck", "withers", "shoulder"], ["frame", "neck", "shoulder", "chest"],
  ["frame", "withers", "back", "rib"], ["frame", "withers", "rib", "shoulder"],
  ["frame", "back", "hip", "waist"], ["frame", "back", "waist", "rib"],
  ["frame", "hip", "rump", "haunch"], ["frame", "hip", "haunch", "waist"],
  ["frame", "rib", "waist", "belly"], ["frame", "waist", "flank", "belly"],
  ["frame", "waist", "haunch", "flank"], ["frame", "shoulder", "rib", "belly"],
  ["frame", "shoulder", "belly", "frontTop"], ["frame", "shoulder", "frontTop", "chest"],
  ["frame", "rump", "rearTop", "haunch"], ["frame", "haunch", "rearTop", "flank"],
  ["tail", "hip", "tailRoot", "rump"], ["tail", "rump", "tailRoot", "tailJoin"],
  ["tail", "tailRoot", "tailBase", "tailBaseOuter"],
  ["tail", "tailRoot", "tailBaseOuter", "tailJoin"],
  ["tail", "tailBase", "tailBend", "tailArc"],
  ["tail", "tailBase", "tailArc", "tailBaseOuter"],
  ["tail", "tailBend", "tailEnd", "tailEndOuter"],
  ["tail", "tailBend", "tailEndOuter", "tailArc"],
  ["tail", "tailEnd", "tailTip", "tailOuter"],
  ["tail", "tailEnd", "tailOuter", "tailEndOuter"],
  ["forelimbs", "chest", "frontKnee", "frontTop"], ["forelimbs", "frontKnee", "frontAnkle", "frontBack"],
  ["forelimbs", "frontKnee", "frontBack", "frontTop"], ["forelimbs", "frontAnkle", "frontToe", "frontPaw"],
  ["forelimbs", "frontAnkle", "frontPaw", "frontHeel"], ["forelimbs", "frontAnkle", "frontHeel", "frontBack"],
  ["forelimbs", "shoulder", "farFrontKnee", "frontTop"], ["forelimbs", "shoulder", "farFrontKnee", "farFrontBack"],
  ["forelimbs", "farFrontKnee", "farFrontAnkle", "farFrontWrist"], ["forelimbs", "farFrontKnee", "farFrontWrist", "farFrontBack"],
  ["forelimbs", "farFrontAnkle", "farFrontToe", "farFrontPaw"], ["forelimbs", "farFrontAnkle", "farFrontPaw", "farFrontHeel"],
  ["forelimbs", "farFrontAnkle", "farFrontHeel", "farFrontWrist"],
  ["hindlegs", "haunch", "rearKnee", "rearTop"], ["hindlegs", "rearKnee", "rearAnkle", "rearHock"],
  ["hindlegs", "rearKnee", "rearHock", "rearTop"], ["hindlegs", "rearAnkle", "rearToe", "rearPaw"],
  ["hindlegs", "rearAnkle", "rearPaw", "rearHeel"], ["hindlegs", "rearAnkle", "rearHeel", "rearHock"],
  ["hindlegs", "flank", "farRearKnee", "haunch"], ["hindlegs", "haunch", "farRearKnee", "farRearBack"],
  ["hindlegs", "farRearKnee", "farRearAnkle", "farRearHock"], ["hindlegs", "farRearKnee", "farRearHock", "farRearBack"],
  ["hindlegs", "farRearAnkle", "farRearToe", "farRearPaw"], ["hindlegs", "farRearAnkle", "farRearPaw", "farRearHeel"],
  ["hindlegs", "farRearAnkle", "farRearHeel", "farRearHock"],
] as const;
