import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

/** Bundle once for both server and file export. No runtime asset requests or CDN. */
const root = resolve(import.meta.dir, "..");
await mkdir(resolve(root, "src/viewer/generated"), { recursive: true });
const worker = await Bun.build({ entrypoints: [resolve(root, "src/viewer/browser/comparison.worker.ts")], target: "browser", format: "iife", minify: true });
if (!worker.success || worker.outputs[0] === undefined) { throw new Error("comparison worker build failed"); }
await Bun.write(resolve(root, "src/viewer/generated/comparison.ts"), `export const comparisonScript = ${JSON.stringify(await worker.outputs[0].text())};\n`);
const result = await Bun.build({
  entrypoints: [resolve(root, "src/viewer/browser/main.ts")],
  target: "browser", format: "iife", minify: true, sourcemap: "none",
});
if (!result.success) { throw new AggregateError(result.logs, "viewer build failed"); }
const js = result.outputs.find((output) => output.path.endsWith(".js"));
const css = result.outputs.find((output) => output.path.endsWith(".css"));
if (js === undefined || css === undefined) { throw new Error("viewer build missing JS or CSS"); }
const script = await js.text();
const styles = await css.text();
await mkdir(resolve(root, "src/viewer/generated"), { recursive: true });
await Bun.write(resolve(root, "src/viewer/generated/assets.ts"),
  `// Generated by bun run build:viewer. Do not edit.\nexport const viewerScript = ${JSON.stringify(script)};\nexport const viewerStyles = ${JSON.stringify(styles)};\n`);
console.log(`viewer built: ${String(script.length)} JS bytes, ${String(styles.length)} CSS bytes`);
