import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

/** Bundle once for both server and file export. No runtime asset requests or CDN. */
const root = resolve(import.meta.dir, "..");
await mkdir(resolve(root, "src/viewer/generated"), { recursive: true });
const puppy = (await Bun.file(resolve(root, "assets/puppy-dag.svg")).text())
  .replace('class="puppy-dag"', 'class="puppy-dag brand-puppy" aria-hidden="true" focusable="false"')
  .replace('viewBox="0 0 1200 840"', 'viewBox="180 180 870 500"');
await Bun.write(resolve(root, "src/viewer/generated/puppy.ts"),
  `// Generated from assets/puppy-dag.svg. Do not edit.\nexport const puppyMarkup = ${JSON.stringify(puppy)};\n`);
const result = await Bun.build({
  entrypoints: [resolve(root, "src/viewer/browser/main.ts")],
  target: "browser", format: "iife", minify: true, sourcemap: "none",
});
if (!result.success) { throw new AggregateError(result.logs, "viewer build failed"); }
const js = result.outputs.find((output) => output.path.endsWith(".js"));
const css = result.outputs.find((output) => output.path.endsWith(".css"));
if (js === undefined || css === undefined) { throw new Error("viewer build missing JS or CSS"); }
const script = await js.text();
const styles = await css.text();
await mkdir(resolve(root, "src/viewer/generated"), { recursive: true });
await Bun.write(resolve(root, "src/viewer/generated/assets.ts"),
  `// Generated by bun run build:viewer. Do not edit.\nexport const viewerScript = ${JSON.stringify(script)};\nexport const viewerStyles = ${JSON.stringify(styles)};\n`);
console.log(`viewer built: ${String(script.length)} JS bytes, ${String(styles.length)} CSS bytes`);
